### ISSUE TITLE
timeout

### ISSUE THREAD

**Issue by emse1981** [Doggi/ioBroker.kostal-piko-mp-plus#40]
Hello, 
i have this error message: timeout of 5000ms exceeded
Can you help me?

Thank you

**Comment by Doggi** [comment]
Hello emse1981,
the adapter uses the XML interface of the Kostal PIKO MP Plus which can be reached under the address http://<ip-address>/all.xml.

You should be able to open it with your browser. Can you test this? 
Just enter the mentioned address in your browser <ip-address> and replace it with the IP of your Kostal PIKO MP Plus.

Which Kostal PIKO do you have exactly, maybe he does not have this interface at all?

**Comment by emse1981** [comment]
Hello, 
Adapter works except for the said message that keeps coming. I get the values ​​that I want, but unfortunately I always get this error in the log.
Interval = 10000ms
Piko 2.5 MP Plus

**Comment by Doggi** [comment]
Hello @emse1981 
That's weird you get data but get a timeout. 
At first it sounds as if the Piko is not always available.
Could you activate the debug logs, maybe you can derive more from it?
